### ISSUE TITLE
Outputting too many positive classifications. Problem with versions of the libraries?

### ISSUE THREAD

**Issue by ycsh-w** [vinay0410/Pedestrian_Detection#3]
Hey there! First of all, let me thank you for your great work!

However, when I was running your code, something weird happens.

I tried to run `python detectmulti.py -i sample_images/pedestrian.jpg` but got the following outcome:
![image](https://user-images.githubusercontent.com/17931662/55287224-c4204000-53d8-11e9-918f-de4791285801.png)
![image](https://user-images.githubusercontent.com/17931662/55287228-d0a49880-53d8-11e9-9ce9-76b22476ec8e.png)

Do you know what goes wrong? I suspect that it is due to the versions of `scikit-learn`, `scikit-image`? I am not so sure.

If you could still run the code successfully, could you please generate a `requirements.txt` to list all the dependencies and their versions?

Thanks in advance!

**Comment by vinay0410** [comment]
Hi @Yuchen-Wang-SH ,
I have fixed these issues, take a fresh pull and then run it.
Also, I have updated the readme to list required deps, with their required versions.

**Comment by vinay0410** [comment]
Hi @Yuchen-Wang-SH ,
Is it working as expected now ?

**Comment by ycsh-w** [comment]
Hey @vinay0410 ! 

Thanks for your fix! I was busy doing other stuff so sorry for my late reply. I just tried your fix and ran `python detectmulti.py -i sample_images/pedestrian.jpg` and it works! I will try to train the model and see if everything works as expected in recent days.

Cheers!
