### ISSUE TITLE
请问这个代码有参考论文吗

### ISSUE THREAD

**Issue by chde222** [vinay0410/Pedestrian_Detection#5]
请问一下，您这个项目有参考论文吗，若有可否说一下论文名

**Comment by vinay0410** [comment]
Translated Version: 
Excuse me, do you have a reference paper for this project?

**Comment by vinay0410** [comment]
Hi @chde222 , You can say that this project is based on [this paper](https://lear.inrialpes.fr/people/triggs/pubs/Dalal-cvpr05.pdf). And uses [this dataset](http://pascal.inrialpes.fr/data/human/).
Although there are some improvements in this implementation.

**Comment by chde222** [comment]
ok thank you very much.
