### ISSUE TITLE
Data set is not availabale

### ISSUE THREAD

**Issue by kalyanharsha** [vinay0410/Pedestrian_Detection#7]

**Comment by vinay0410** [comment]
Link to dataset is already mentioned in the readme and it is not broken, therefore closing this.
Feel free to reopen this, if you face any issues.

**Comment by vinay0410** [comment]
@kalyanharsha , You can now download dataset from the following link.
https://drive.google.com/file/d/14GD_pBpBsprPiZlkmtXN_y5K72To16if/view?usp=sharing
