### ISSUE TITLE
Which version of packages were used?

### ISSUE THREAD

**Issue by NarasimhaD01** [vinay0410/Pedestrian_Detection#8]
I am getting issues while running the .py code as I am getting many issues due to incorrect version of packages.
@vinay0410 : Could you please list out the version of:
1. numpy
2. opencv

I would appreciate if anyone else who have executed could answer.
Thanks in advance! Have a nice day.

**Comment by vinay0410** [comment]
Are you certain that you are getting errors because of incorrect versions ?
I use numpy and opencv for minor things only, and I don't think it should break no matter the version.
It would be better for me to debug if you could post the errors, along with the output of `pip freeze`

**Comment by NarasimhaD01** [comment]
Kindly find the below: When I am trying to train the datasets, I am getting below comments:
Note: I am using numpy version 1.16.

python train.py --pos /home/pi/Desktop/Thesis/Pedestrian_Detection-master/INRIAPerson/Train/pos
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from skimage.feature import hog
  File "/usr/local/lib/python3.7/dist-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "/usr/local/lib/python3.7/dist-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/usr/local/lib/python3.7/dist-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (/usr/lib/python3/dist-packages/numpy/lib/arraypad.py)

**Comment by NarasimhaD01** [comment]
I could solve the issue for the above mentioned error.
I had installed a previous version of Scikit-image and it posed the trouble.

Could you please help me with following issue:
When I tried training the datasets, I got following issue:

python train.py --pos INRIAPerson/train_64x128_H96/pos 
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    pos_img_files, neg_img_files = read_filenames()
  File "train.py", line 60, in read_filenames
    for (dirpath, dirnames, filenames) in os.walk(mypath_neg):
  File "/usr/lib/python3.7/os.py", line 336, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by NarasimhaD01** [comment]
Hello,

**I have made some changes in the train.py file to fit the environment.**
[train.zip](https://github.com/vinay0410/Pedestrian_Detection/files/5290888/train.zip)

**But, for this I am getting compilation error:**

python train.py --pos INRIAPerson/train_64x128_H96/pos
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    pos_img_files, neg_img_files = read_filenames()
  File "train.py", line 60, in read_filenames
    for (dirpath, dirnames, filenames) in os.walk(mypath_neg):
  File "/usr/lib/python3.7/os.py", line 336, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Could anyone please help me in fixing the issue?
I am badly stuck.**

**Comment by vinay0410** [comment]
> I could solve the issue for the above mentioned error.
> I had installed a previous version of Scikit-image and it posed the trouble.
> 
> Could you please help me with following issue:
> When I tried training the datasets, I got following issue:
> 
> python train.py --pos INRIAPerson/train_64x128_H96/pos
> Traceback (most recent call last):
>   File "train.py", line 161, in
>     pos_img_files, neg_img_files = read_filenames()
>   File "train.py", line 60, in read_filenames
>     for (dirpath, dirnames, filenames) in os.walk(mypath_neg):
>   File "/usr/lib/python3.7/os.py", line 336, in walk
>     top = fspath(top)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

I think this means that the directory you are trying to walk is either non existent or empty. So, could verify if `INRIAPerson/train_64x128_H96/pos` is present and has something.

**Comment by vinay0410** [comment]
Also @NarasimhaD01 , I see that you are using python3 that might also be an issue, since this code was originally written in `python2`. Try to see if you still get the same errors when using `python2`.

**Comment by NarasimhaD01** [comment]
> > I could solve the issue for the above mentioned error.
> > I had installed a previous version of Scikit-image and it posed the trouble.
> > Could you please help me with following issue:
> > When I tried training the datasets, I got following issue:
> > python train.py --pos INRIAPerson/train_64x128_H96/pos
> > Traceback (most recent call last):
> >   File "train.py", line 161, in
> >     pos_img_files, neg_img_files = read_filenames()
> >   File "train.py", line 60, in read_filenames
> >     for (dirpath, dirnames, filenames) in os.walk(mypath_neg):
> >   File "/usr/lib/python3.7/os.py", line 336, in walk
> >     top = fspath(top)
> > TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> I think this means that the directory you are trying to walk is either non existent or empty. So, could verify if `INRIAPerson/train_64x128_H96/pos` is present and has something.

I could confirm that images are present in that location. To add to it, the images are named crop**** after running the shell file.

**Comment by NarasimhaD01** [comment]
> Also @NarasimhaD01 , I see that you are using python3 that might also be an issue, since this code was originally written in `python2`. Try to see if you still get the same errors when using `python2`.

**Hello @vinay0410 : I have tried running on python2 (2.7.16)

After running the train.py and test.py, I get the following error:**

python2 test.py --pos INRIAPerson/test_64x128_H96/pos 
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    clf = joblib.load('person_final.pkl')
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

python2 train.py --pos INRIAPerson/train_64x128_H96/pos
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    pos_img_files, neg_img_files = read_filenames()
  File "train.py", line 60, in read_filenames
    for (dirpath, dirnames, filenames) in os.walk(mypath_neg):
  File "/usr/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Could you please suggest solution ?**

**Comment by vinay0410** [comment]
The first error seems to be a version conflict between pickling of python3 and python2. Ensure that `person_final.pkl` hasn't been changed. I think using python3 previously might have overwritten this file.
In the second command I guess you forgot to pass `--neg`.

I haven't been able to replicate the same on my system, so I am sure that there isn't any problem with the code.
Also, please follow the instructions mentioned in the readme, and ensure that you haven't missed any of those.

Let me know if still get any errors.

**Comment by vinay0410** [comment]
Also I suggest creating a virtualenv and then installing mentioned dependencies. So, that there are no conflicts.

**Comment by NarasimhaD01** [comment]
> Also I suggest creating a virtualenv and then installing mentioned dependencies. So, that there are no conflicts.

Could you suggest what will be the dependencies to be installed after creating virtualenv?

**Comment by NarasimhaD01** [comment]
> The first error seems to be a version conflict between pickling of python3 and python2. Ensure that `person_final.pkl` hasn't been changed. I think using python3 previously might have overwritten this file.
> In the second command I guess you forgot to pass `--neg`.
> 
> I haven't been able to replicate the same on my system, so I am sure that there isn't any problem with the code.
> Also, please follow the instructions mentioned in the readme, and ensure that you haven't missed any of those.
> 
> Let me know if still get any errors.

Hello @vinay0410 : Yes, the person_final.pkl file was changed. So I replaced the file from Git.
But now after replacing the file, I am getting different error related to pickle problem:

python2 train.py --pos INRIAPerson/train_64x128_H96/pos
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    pos_img_files, neg_img_files = read_filenames()
  File "train.py", line 60, in read_filenames
    for (dirpath, dirnames, filenames) in os.walk(mypath_neg):
  File "/usr/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found

python2 test.py --pos INRIAPerson/Test/pos
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    clf = joblib.load('person_final.pkl')
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '\x00'

**This issue got solved by adding the --neg command in terminal.**

**Comment by NarasimhaD01** [comment]
I could now run the train the dataset.
But at the end of the training, this error comes:
Maximum Hard Negatives to Mine: 20000
	Hard Negatives Mined: 786ompleteCompleted: 3.93 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 890	Completed: 4.45 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 2098	Completed: 10.49 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 3143	Completed: 15.715 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 5359	Completed: 26.795 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 5755	Completed: 28.775 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 6119	Completed: 30.595 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 9681	Completed: 48.405 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 10277	Completed: 51.385 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 10422	Completed: 52.11 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 10461	Completed: 52.305 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 13791	Completed: 68.955 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 15956	Completed: 79.78 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 16810	Completed: 84.05 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 16831	Completed: 84.155 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 18168	Completed: 90.84 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 18313	Completed: 91.565 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 18787	Completed: 93.935 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19299	Completed: 96.495 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19389	Completed: 96.945 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19998	Completed: 99.99 %%
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    hard_negatives = np.concatenate((hard_negatives, X), axis = 0)
MemoryError


**Could you please suggest the solution?**

**Comment by vinay0410** [comment]
Please read the the readme thoroughly. Did you fix your pngs as mentioned in the readme ?

**Comment by NarasimhaD01** [comment]
@vinay0410 : **Note : I am running this code in raspberry pii with 4GB RAM.**

**I have already run the fixing.sh file.**
**Still I could get the following issue:**

Images Read and Shuffled
Positives: 2416
Negatives: 12180
Training Started
[LibLinear]....*
optimization finished, #iter = 47
Objective value = -8.129533
nSV = 2418
Trained
Hard Negative Mining
Maximum Hard Negatives to Mine: 20000
	Hard Negatives Mined: 745ompleteCompleted: 3.725 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 816	Completed: 4.08 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 1973	Completed: 9.865 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 3018	Completed: 15.09 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 5050	Completed: 25.25 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 5415	Completed: 27.075 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 5733	Completed: 28.665 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 8989	Completed: 44.945 %libpng warning: iCCP: known incorrect sRGB profile                                            
	Hard Negatives Mined: 9530	Completed: 47.65 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 9652	Completed: 48.26 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 9689	Completed: 48.445 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 12709	Completed: 63.545 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 14720	Completed: 73.6 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 15597	Completed: 77.985 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 15620	Completed: 78.1 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 16912	Completed: 84.56 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 17048	Completed: 85.24 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 17475	Completed: 87.375 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 17927	Completed: 89.635 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 18001	Completed: 90.005 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19022	Completed: 95.11 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19401	Completed: 97.005 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19482	Completed: 97.41 %libpng warning: iCCP: known incorrect sRGB profile
	Hard Negatives Mined: 19996	Completed: 99.98 %%
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    hard_negatives = np.concatenate((hard_negatives, X), axis = 0)
**MemoryError**

Could you please suggest?

**Comment by vinay0410** [comment]
Ram size is only relevant if you don’t have swap allocated. It is possible possible that raspberry pi doesn’t have enough memory, you can verify the same by logging memory usage.

If that’s not feasible allocate swap.

**Comment by NarasimhaD01** [comment]
> Ram size is only relevant if you don’t have swap allocated. It is possible possible that raspberry pi doesn’t have enough memory, you can verify the same by logging memory usage. If that’s not feasible allocate swap.
> […](#)
> On 01-Oct-2020, at 7:50 PM, NarasimhaD01 ***@***.***> wrote: ﻿ @vinay0410 : **Note : I am running this code in raspberry pii with 4GB RAM. I have already run the fixing.sh file. Still I could get the following issue:** Images Read and Shuffled Positives: 2416 Negatives: 12180 Training Started [LibLinear]....* optimization finished, #iter = 47 Objective value = -8.129533 nSV = 2418 Trained Hard Negative Mining Maximum Hard Negatives to Mine: 20000 Hard Negatives Mined: 745ompleteCompleted: 3.725 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 816 Completed: 4.08 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 1973 Completed: 9.865 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 3018 Completed: 15.09 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 5050 Completed: 25.25 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 5415 Completed: 27.075 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 5733 Completed: 28.665 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 8989 Completed: 44.945 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 9530 Completed: 47.65 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 9652 Completed: 48.26 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 9689 Completed: 48.445 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 12709 Completed: 63.545 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 14720 Completed: 73.6 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 15597 Completed: 77.985 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 15620 Completed: 78.1 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 16912 Completed: 84.56 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 17048 Completed: 85.24 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 17475 Completed: 87.375 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 17927 Completed: 89.635 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 18001 Completed: 90.005 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 19022 Completed: 95.11 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 19401 Completed: 97.005 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 19482 Completed: 97.41 %libpng warning: iCCP: known incorrect sRGB profile Hard Negatives Mined: 19996 Completed: 99.98 %% Traceback (most recent call last): File "train.py", line 199, in hard_negatives = np.concatenate((hard_negatives, X), axis = 0) MemoryError Could you please suggest? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Should I increase the swap size ?**

**Comment by NarasimhaD01** [comment]
i have increased the swap size and run the training command.
I could see training happened on both png and jpg files.

Question: 1. after running fixing.sh, should all the files get converted to .png extension?
2. How can i clear this issue: (please open error log)
[Error_log.txt](https://github.com/vinay0410/Pedestrian_Detection/files/5316440/Error_log.txt)

**I am Stuck, please support!**

**Comment by vinay0410** [comment]
You haven't answered my previous questions, why are you trying to train this on a raspberry pi ?
You can very well train this on your laptop and then move the trained inferencer to raspberry pi for detection. 
And if your goal is to detect pedestrians only, why can't you use already trained inferencers present in the repository. You won't get any better performance by retraining.

And did you try to log amount of memory used so, that you can get a clear idea, how much ram is necessary, as suggested previously ?

**Comment by vinay0410** [comment]
I don't have any means to test this on a raspberry pi, and it is not meant to be trained on a raspberry pi. I will try to get a rough idea of the amount of memory required while training this on my computer. But that's all I can do.

**Comment by vinay0410** [comment]
I replicated everything on my machine from scratch, and it took 12Gs of swap max, but it may vary depending on the OS. Since some operating systems compress data before storing it into RAM, and my OS is one of them.
So, Raspberry Pi might need more swap than that. If you are very hell-bent on using Raspberry Pi for training, then I would suggest increasing swap as much as possible, and then measure max amount of swap used during the whole training process, and then shrink your swap to fit the same.

Anyways, this is no longer an issue with this repo, therefore closing this.

**Comment by NarasimhaD01** [comment]
> You haven't answered my previous questions, why are you trying to train this on a raspberry pi ?
> You can very well train this on your laptop and then move the trained inferencer to raspberry pi for detection.
> And if your goal is to detect pedestrians only, why can't you use already trained inferencers present in the repository. You won't get any better performance by retraining.
> 
> And did you try to log amount of memory used so, that you can get a clear idea, how much ram is necessary, as suggested previously ?

Hello Vinay,
Sorry, I was in a vacation so couldnt check the messages.
Yes, I need to do it into a raspberry pi machine as this is the demand of the project.
So, I could run your train.py and test.py into the machine.

For furture reference: If anyone wants to use Your code into Raspberry pi machine.
1. Use the 64 bit raspbian OS / Noobs Os.
2. Use the SD card with minimum 64 GB memory.
It worked well for me with above configuration.

Also, to answer the RAM memory constraints, so far no issues related to RAM size for the above mentioned environment.

**Comment by NarasimhaD01** [comment]
> I replicated everything on my machine from scratch, and it took 12Gs of swap max, but it may vary depending on the OS. Since some operating systems compress data before storing it into RAM, and my OS is one of them.
> So, Raspberry Pi might need more swap than that. If you are very hell-bent on using Raspberry Pi for training, then I would suggest increasing swap as much as possible, and then measure max amount of swap used during the whole training process, and then shrink your swap to fit the same.
> 
> Anyways, this is no longer an issue with this repo, therefore closing this.

Yes, absolutely correct.
I wanted to run the pedestrian detection application into a raspberry pi system, which was mandatory observation.
Meanwhile I will share the results I could run into the raspberry pi machine here.
